import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Topbar from '@/components/Topbar';
import Navbar from '@/components/Navbar';
import Sidebar from '@/components/Sidebar';
import TabInfo from '@/components/edit-profile/TabInfo';

export default function Home() {
  return (
    <>
      <Head>
        <title>User Design Test</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Topbar />
        <Navbar active='home' />
        <main className={styles.home_main_container}>
          <Sidebar active='edit profile' />
          <TabInfo />
        </main>
      </div>
    </>
  )
}
